// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customer-service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoadByIDRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadByIDRequest) Reset()         { *m = LoadByIDRequest{} }
func (m *LoadByIDRequest) String() string { return proto.CompactTextString(m) }
func (*LoadByIDRequest) ProtoMessage()    {}
func (*LoadByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e11e6f9e510dc23e, []int{0}
}

func (m *LoadByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadByIDRequest.Unmarshal(m, b)
}
func (m *LoadByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadByIDRequest.Marshal(b, m, deterministic)
}
func (m *LoadByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadByIDRequest.Merge(m, src)
}
func (m *LoadByIDRequest) XXX_Size() int {
	return xxx_messageInfo_LoadByIDRequest.Size(m)
}
func (m *LoadByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadByIDRequest proto.InternalMessageInfo

func (m *LoadByIDRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LoadByPhoneRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadByPhoneRequest) Reset()         { *m = LoadByPhoneRequest{} }
func (m *LoadByPhoneRequest) String() string { return proto.CompactTextString(m) }
func (*LoadByPhoneRequest) ProtoMessage()    {}
func (*LoadByPhoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e11e6f9e510dc23e, []int{1}
}

func (m *LoadByPhoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadByPhoneRequest.Unmarshal(m, b)
}
func (m *LoadByPhoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadByPhoneRequest.Marshal(b, m, deterministic)
}
func (m *LoadByPhoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadByPhoneRequest.Merge(m, src)
}
func (m *LoadByPhoneRequest) XXX_Size() int {
	return xxx_messageInfo_LoadByPhoneRequest.Size(m)
}
func (m *LoadByPhoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadByPhoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadByPhoneRequest proto.InternalMessageInfo

func (m *LoadByPhoneRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type LoadCustomerResponse struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string               `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	RegisteregAt         *timestamp.Timestamp `protobuf:"bytes,3,opt,name=registereg_at,json=registeregAt,proto3" json:"registereg_at,omitempty"`
	StatusId             uint64               `protobuf:"varint,4,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	ReferrerId           uint64               `protobuf:"varint,5,opt,name=referrer_id,json=referrerId,proto3" json:"referrer_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LoadCustomerResponse) Reset()         { *m = LoadCustomerResponse{} }
func (m *LoadCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*LoadCustomerResponse) ProtoMessage()    {}
func (*LoadCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e11e6f9e510dc23e, []int{2}
}

func (m *LoadCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadCustomerResponse.Unmarshal(m, b)
}
func (m *LoadCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadCustomerResponse.Marshal(b, m, deterministic)
}
func (m *LoadCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadCustomerResponse.Merge(m, src)
}
func (m *LoadCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_LoadCustomerResponse.Size(m)
}
func (m *LoadCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadCustomerResponse proto.InternalMessageInfo

func (m *LoadCustomerResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoadCustomerResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LoadCustomerResponse) GetRegisteregAt() *timestamp.Timestamp {
	if m != nil {
		return m.RegisteregAt
	}
	return nil
}

func (m *LoadCustomerResponse) GetStatusId() uint64 {
	if m != nil {
		return m.StatusId
	}
	return 0
}

func (m *LoadCustomerResponse) GetReferrerId() uint64 {
	if m != nil {
		return m.ReferrerId
	}
	return 0
}

func (m *LoadCustomerResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *LoadCustomerResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type NewCustomerRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	StatusId             uint64   `protobuf:"varint,3,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	ReferrerId           uint64   `protobuf:"varint,4,opt,name=referrer_id,json=referrerId,proto3" json:"referrer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewCustomerRequest) Reset()         { *m = NewCustomerRequest{} }
func (m *NewCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*NewCustomerRequest) ProtoMessage()    {}
func (*NewCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e11e6f9e510dc23e, []int{3}
}

func (m *NewCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewCustomerRequest.Unmarshal(m, b)
}
func (m *NewCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewCustomerRequest.Marshal(b, m, deterministic)
}
func (m *NewCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewCustomerRequest.Merge(m, src)
}
func (m *NewCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_NewCustomerRequest.Size(m)
}
func (m *NewCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewCustomerRequest proto.InternalMessageInfo

func (m *NewCustomerRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *NewCustomerRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *NewCustomerRequest) GetStatusId() uint64 {
	if m != nil {
		return m.StatusId
	}
	return 0
}

func (m *NewCustomerRequest) GetReferrerId() uint64 {
	if m != nil {
		return m.ReferrerId
	}
	return 0
}

type Error struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_e11e6f9e510dc23e, []int{4}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type LoginRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e11e6f9e510dc23e, []int{5}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*LoadByIDRequest)(nil), "pb.LoadByIDRequest")
	proto.RegisterType((*LoadByPhoneRequest)(nil), "pb.LoadByPhoneRequest")
	proto.RegisterType((*LoadCustomerResponse)(nil), "pb.LoadCustomerResponse")
	proto.RegisterType((*NewCustomerRequest)(nil), "pb.NewCustomerRequest")
	proto.RegisterType((*Error)(nil), "pb.Error")
	proto.RegisterType((*LoginRequest)(nil), "pb.LoginRequest")
}

func init() { proto.RegisterFile("customer-service.proto", fileDescriptor_e11e6f9e510dc23e) }

var fileDescriptor_e11e6f9e510dc23e = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0x35, 0xd9, 0xa6, 0xb6, 0xb7, 0xeb, 0x07, 0xe3, 0x52, 0x42, 0x44, 0x76, 0xcd, 0xd3, 0x22,
	0x98, 0x85, 0x15, 0x1f, 0x44, 0x41, 0x63, 0x15, 0x09, 0x2c, 0x52, 0xa2, 0xef, 0x4b, 0xd2, 0xb9,
	0x8d, 0x01, 0xdb, 0x19, 0x67, 0x26, 0x16, 0xdf, 0x7d, 0xf5, 0xc7, 0xf8, 0x0f, 0x65, 0x66, 0x32,
	0xa6, 0xb6, 0x92, 0xc2, 0xbe, 0xcd, 0xbd, 0x73, 0xce, 0x9c, 0x39, 0x87, 0x03, 0xd3, 0x45, 0x23,
	0x15, 0x5b, 0xa1, 0x78, 0x2a, 0x51, 0x7c, 0xaf, 0x17, 0x98, 0x70, 0xc1, 0x14, 0x23, 0x3e, 0x2f,
	0xa3, 0xd3, 0x8a, 0xb1, 0xea, 0x2b, 0x5e, 0x98, 0x4d, 0xd9, 0x2c, 0x2f, 0x54, 0xbd, 0x42, 0xa9,
	0x8a, 0x15, 0xb7, 0xa0, 0xf8, 0x31, 0xdc, 0xbb, 0x62, 0x05, 0x7d, 0xfb, 0x23, 0x7b, 0x97, 0xe3,
	0xb7, 0x06, 0xa5, 0x22, 0x77, 0xc1, 0xaf, 0x69, 0xe8, 0x9d, 0x79, 0xe7, 0x83, 0xdc, 0xaf, 0x69,
	0xfc, 0x04, 0x88, 0x85, 0xcc, 0xbf, 0xb0, 0x35, 0x3a, 0xd4, 0x09, 0x04, 0x5c, 0xcf, 0x06, 0x38,
	0xce, 0xed, 0x10, 0xff, 0xf6, 0xe1, 0x44, 0x83, 0x67, 0xed, 0x97, 0x72, 0x94, 0x9c, 0xad, 0x25,
	0xee, 0x3e, 0xda, 0xd1, 0xfd, 0x2d, 0x3a, 0x79, 0x0d, 0x77, 0x04, 0x56, 0xb5, 0x54, 0x28, 0xb0,
	0xba, 0x2e, 0x54, 0x78, 0x74, 0xe6, 0x9d, 0x4f, 0x2e, 0xa3, 0xc4, 0xda, 0x48, 0x9c, 0x8d, 0xe4,
	0xb3, 0xb3, 0x91, 0x1f, 0x77, 0x84, 0x54, 0x91, 0x87, 0x30, 0x96, 0xaa, 0x50, 0x8d, 0xbc, 0xae,
	0x69, 0x38, 0x30, 0x6a, 0x23, 0xbb, 0xc8, 0x28, 0x39, 0x85, 0x89, 0xc0, 0x25, 0x0a, 0x81, 0x42,
	0x5f, 0x07, 0xe6, 0x1a, 0xdc, 0x2a, 0xa3, 0xe4, 0x05, 0xc0, 0x42, 0x60, 0xa1, 0x90, 0x6a, 0xed,
	0xe1, 0x41, 0xed, 0x71, 0x8b, 0x4e, 0x95, 0xa6, 0x36, 0x9c, 0x3a, 0xea, 0xed, 0xc3, 0xd4, 0x16,
	0x9d, 0xaa, 0xf8, 0xa7, 0x07, 0xe4, 0x23, 0x6e, 0xba, 0xc8, 0x7a, 0x02, 0x26, 0x11, 0x8c, 0x78,
	0x21, 0xe5, 0x86, 0x09, 0xda, 0x46, 0xf7, 0x77, 0xfe, 0xd7, 0xfc, 0x51, 0xbf, 0xf9, 0xc1, 0xae,
	0xf9, 0xf8, 0x11, 0x04, 0xef, 0x85, 0x60, 0x42, 0x0b, 0xa3, 0x3e, 0x38, 0x61, 0x33, 0xc4, 0x6f,
	0xe0, 0xf8, 0x8a, 0x55, 0xf5, 0xfa, 0xc6, 0xdf, 0xbb, 0xfc, 0xe5, 0xc3, 0xd4, 0x99, 0x4c, 0xe7,
	0xd9, 0x27, 0x5b, 0xd6, 0x0f, 0xf9, 0x7c, 0x46, 0x5e, 0xc1, 0x70, 0x66, 0xa2, 0x24, 0xd3, 0x84,
	0x97, 0xc9, 0x7e, 0x1a, 0x51, 0xa8, 0xf7, 0xff, 0x6b, 0x56, 0x7c, 0x8b, 0xbc, 0x84, 0x91, 0xeb,
	0x30, 0x79, 0xe0, 0x70, 0x5b, 0x8d, 0xee, 0x25, 0xa7, 0x30, 0xd9, 0x6a, 0xb7, 0xd5, 0xdf, 0xaf,
	0x7b, 0xef, 0x13, 0xcf, 0x21, 0x30, 0xd1, 0x90, 0xfb, 0x16, 0xd4, 0xa5, 0xd4, 0x47, 0x2b, 0x87,
	0xa6, 0x16, 0xcf, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x02, 0xdf, 0x2a, 0xc0, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerAPIServiceGRPCClient is the client API for CustomerAPIServiceGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerAPIServiceGRPCClient interface {
	Create(ctx context.Context, in *NewCustomerRequest, opts ...grpc.CallOption) (*LoadCustomerResponse, error)
	LoadByID(ctx context.Context, in *LoadByIDRequest, opts ...grpc.CallOption) (*LoadCustomerResponse, error)
	LoadByPhone(ctx context.Context, in *LoadByPhoneRequest, opts ...grpc.CallOption) (*LoadCustomerResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoadCustomerResponse, error)
}

type customerAPIServiceGRPCClient struct {
	cc *grpc.ClientConn
}

func NewCustomerAPIServiceGRPCClient(cc *grpc.ClientConn) CustomerAPIServiceGRPCClient {
	return &customerAPIServiceGRPCClient{cc}
}

func (c *customerAPIServiceGRPCClient) Create(ctx context.Context, in *NewCustomerRequest, opts ...grpc.CallOption) (*LoadCustomerResponse, error) {
	out := new(LoadCustomerResponse)
	err := c.cc.Invoke(ctx, "/pb.CustomerAPIServiceGRPC/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerAPIServiceGRPCClient) LoadByID(ctx context.Context, in *LoadByIDRequest, opts ...grpc.CallOption) (*LoadCustomerResponse, error) {
	out := new(LoadCustomerResponse)
	err := c.cc.Invoke(ctx, "/pb.CustomerAPIServiceGRPC/LoadByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerAPIServiceGRPCClient) LoadByPhone(ctx context.Context, in *LoadByPhoneRequest, opts ...grpc.CallOption) (*LoadCustomerResponse, error) {
	out := new(LoadCustomerResponse)
	err := c.cc.Invoke(ctx, "/pb.CustomerAPIServiceGRPC/LoadByPhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerAPIServiceGRPCClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoadCustomerResponse, error) {
	out := new(LoadCustomerResponse)
	err := c.cc.Invoke(ctx, "/pb.CustomerAPIServiceGRPC/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerAPIServiceGRPCServer is the server API for CustomerAPIServiceGRPC service.
type CustomerAPIServiceGRPCServer interface {
	Create(context.Context, *NewCustomerRequest) (*LoadCustomerResponse, error)
	LoadByID(context.Context, *LoadByIDRequest) (*LoadCustomerResponse, error)
	LoadByPhone(context.Context, *LoadByPhoneRequest) (*LoadCustomerResponse, error)
	Login(context.Context, *LoginRequest) (*LoadCustomerResponse, error)
}

func RegisterCustomerAPIServiceGRPCServer(s *grpc.Server, srv CustomerAPIServiceGRPCServer) {
	s.RegisterService(&_CustomerAPIServiceGRPC_serviceDesc, srv)
}

func _CustomerAPIServiceGRPC_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAPIServiceGRPCServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CustomerAPIServiceGRPC/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAPIServiceGRPCServer).Create(ctx, req.(*NewCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerAPIServiceGRPC_LoadByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAPIServiceGRPCServer).LoadByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CustomerAPIServiceGRPC/LoadByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAPIServiceGRPCServer).LoadByID(ctx, req.(*LoadByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerAPIServiceGRPC_LoadByPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadByPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAPIServiceGRPCServer).LoadByPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CustomerAPIServiceGRPC/LoadByPhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAPIServiceGRPCServer).LoadByPhone(ctx, req.(*LoadByPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerAPIServiceGRPC_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAPIServiceGRPCServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CustomerAPIServiceGRPC/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAPIServiceGRPCServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomerAPIServiceGRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CustomerAPIServiceGRPC",
	HandlerType: (*CustomerAPIServiceGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CustomerAPIServiceGRPC_Create_Handler,
		},
		{
			MethodName: "LoadByID",
			Handler:    _CustomerAPIServiceGRPC_LoadByID_Handler,
		},
		{
			MethodName: "LoadByPhone",
			Handler:    _CustomerAPIServiceGRPC_LoadByPhone_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _CustomerAPIServiceGRPC_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer-service.proto",
}
