// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customer-service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoadByIDRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadByIDRequest) Reset()         { *m = LoadByIDRequest{} }
func (m *LoadByIDRequest) String() string { return proto.CompactTextString(m) }
func (*LoadByIDRequest) ProtoMessage()    {}
func (*LoadByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e11e6f9e510dc23e, []int{0}
}

func (m *LoadByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadByIDRequest.Unmarshal(m, b)
}
func (m *LoadByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadByIDRequest.Marshal(b, m, deterministic)
}
func (m *LoadByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadByIDRequest.Merge(m, src)
}
func (m *LoadByIDRequest) XXX_Size() int {
	return xxx_messageInfo_LoadByIDRequest.Size(m)
}
func (m *LoadByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadByIDRequest proto.InternalMessageInfo

func (m *LoadByIDRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LoadByEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadByEmailRequest) Reset()         { *m = LoadByEmailRequest{} }
func (m *LoadByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*LoadByEmailRequest) ProtoMessage()    {}
func (*LoadByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e11e6f9e510dc23e, []int{1}
}

func (m *LoadByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadByEmailRequest.Unmarshal(m, b)
}
func (m *LoadByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadByEmailRequest.Marshal(b, m, deterministic)
}
func (m *LoadByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadByEmailRequest.Merge(m, src)
}
func (m *LoadByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_LoadByEmailRequest.Size(m)
}
func (m *LoadByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadByEmailRequest proto.InternalMessageInfo

func (m *LoadByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type LoadCustomerResponse struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string               `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	RegisteregAt         *timestamp.Timestamp `protobuf:"bytes,3,opt,name=registereg_at,json=registeregAt,proto3" json:"registereg_at,omitempty"`
	StatusId             int32                `protobuf:"varint,4,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LoadCustomerResponse) Reset()         { *m = LoadCustomerResponse{} }
func (m *LoadCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*LoadCustomerResponse) ProtoMessage()    {}
func (*LoadCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e11e6f9e510dc23e, []int{2}
}

func (m *LoadCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadCustomerResponse.Unmarshal(m, b)
}
func (m *LoadCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadCustomerResponse.Marshal(b, m, deterministic)
}
func (m *LoadCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadCustomerResponse.Merge(m, src)
}
func (m *LoadCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_LoadCustomerResponse.Size(m)
}
func (m *LoadCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadCustomerResponse proto.InternalMessageInfo

func (m *LoadCustomerResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoadCustomerResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LoadCustomerResponse) GetRegisteregAt() *timestamp.Timestamp {
	if m != nil {
		return m.RegisteregAt
	}
	return nil
}

func (m *LoadCustomerResponse) GetStatusId() int32 {
	if m != nil {
		return m.StatusId
	}
	return 0
}

func (m *LoadCustomerResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *LoadCustomerResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type NewCustomerRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	StatusId             int32    `protobuf:"varint,3,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewCustomerRequest) Reset()         { *m = NewCustomerRequest{} }
func (m *NewCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*NewCustomerRequest) ProtoMessage()    {}
func (*NewCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e11e6f9e510dc23e, []int{3}
}

func (m *NewCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewCustomerRequest.Unmarshal(m, b)
}
func (m *NewCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewCustomerRequest.Marshal(b, m, deterministic)
}
func (m *NewCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewCustomerRequest.Merge(m, src)
}
func (m *NewCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_NewCustomerRequest.Size(m)
}
func (m *NewCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewCustomerRequest proto.InternalMessageInfo

func (m *NewCustomerRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *NewCustomerRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *NewCustomerRequest) GetStatusId() int32 {
	if m != nil {
		return m.StatusId
	}
	return 0
}

type Error struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_e11e6f9e510dc23e, []int{4}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*LoadByIDRequest)(nil), "pb.LoadByIDRequest")
	proto.RegisterType((*LoadByEmailRequest)(nil), "pb.LoadByEmailRequest")
	proto.RegisterType((*LoadCustomerResponse)(nil), "pb.LoadCustomerResponse")
	proto.RegisterType((*NewCustomerRequest)(nil), "pb.NewCustomerRequest")
	proto.RegisterType((*Error)(nil), "pb.Error")
}

func init() { proto.RegisterFile("customer-service.proto", fileDescriptor_e11e6f9e510dc23e) }

var fileDescriptor_e11e6f9e510dc23e = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x5d, 0x8b, 0xda, 0x40,
	0x14, 0x25, 0xd1, 0x88, 0xb9, 0xf6, 0x03, 0xa6, 0x22, 0x21, 0xa5, 0xd4, 0xe6, 0x49, 0x5a, 0x1a,
	0xc1, 0x3e, 0xf9, 0x24, 0xa9, 0xf5, 0x41, 0x28, 0xa5, 0xa4, 0x7d, 0x97, 0x24, 0x73, 0x9b, 0x06,
	0x8c, 0x33, 0x3b, 0x33, 0x59, 0xd9, 0x7f, 0xb1, 0x7f, 0x68, 0xff, 0xdb, 0x32, 0x99, 0xc4, 0x4f,
	0x16, 0xdf, 0x72, 0x0f, 0xe7, 0x9c, 0xcc, 0xb9, 0xf7, 0xc0, 0x28, 0xab, 0xa4, 0x62, 0x25, 0x8a,
	0xaf, 0x12, 0xc5, 0x7d, 0x91, 0x61, 0xc8, 0x05, 0x53, 0x8c, 0xd8, 0x3c, 0xf5, 0x3f, 0xe6, 0x8c,
	0xe5, 0x5b, 0x9c, 0xd6, 0x48, 0x5a, 0xfd, 0x9b, 0xaa, 0xa2, 0x44, 0xa9, 0x92, 0x92, 0x1b, 0x52,
	0xf0, 0x09, 0xde, 0xfe, 0x64, 0x09, 0xfd, 0xfe, 0xb0, 0xfe, 0x11, 0xe3, 0x5d, 0x85, 0x52, 0x91,
	0x37, 0x60, 0x17, 0xd4, 0xb3, 0xc6, 0xd6, 0xa4, 0x1b, 0xdb, 0x05, 0x0d, 0x3e, 0x03, 0x31, 0x94,
	0x55, 0x99, 0x14, 0xdb, 0x96, 0x35, 0x04, 0x07, 0xf5, 0x5c, 0x13, 0xdd, 0xd8, 0x0c, 0xc1, 0xa3,
	0x0d, 0x43, 0x4d, 0x5e, 0x36, 0x4f, 0x8a, 0x51, 0x72, 0xb6, 0x93, 0x78, 0x69, 0xaa, 0xe5, 0xfc,
	0x3f, 0xdb, 0xa1, 0x67, 0x1b, 0x79, 0x3d, 0x90, 0x05, 0xbc, 0x16, 0x98, 0x17, 0x52, 0xa1, 0xc0,
	0x7c, 0x93, 0x28, 0xaf, 0x33, 0xb6, 0x26, 0x83, 0x99, 0x1f, 0x9a, 0x18, 0x61, 0x1b, 0x23, 0xfc,
	0xdb, 0xc6, 0x88, 0x5f, 0x1d, 0x05, 0x91, 0x22, 0xef, 0xc1, 0x95, 0x2a, 0x51, 0x95, 0xdc, 0x14,
	0xd4, 0xeb, 0x8e, 0xad, 0x89, 0x13, 0xf7, 0x0d, 0xb0, 0xa6, 0x64, 0x0e, 0x90, 0x09, 0x4c, 0x14,
	0x52, 0x6d, 0xed, 0xdc, 0xb4, 0x76, 0x1b, 0x76, 0xa4, 0xb4, 0xb4, 0xe2, 0xb4, 0x95, 0xf6, 0x6e,
	0x4b, 0x1b, 0x76, 0xa4, 0x82, 0x0c, 0xc8, 0x2f, 0xdc, 0x1f, 0x17, 0x72, 0x58, 0x9f, 0xc9, 0x6f,
	0x9d, 0xe6, 0xf7, 0xa1, 0xcf, 0x13, 0x29, 0xf7, 0x4c, 0xd0, 0x66, 0x31, 0x87, 0xf9, 0x3c, 0x5a,
	0xe7, 0x3c, 0x5a, 0xf0, 0x01, 0x9c, 0x95, 0x10, 0x4c, 0xd4, 0x67, 0xd1, 0x1f, 0x87, 0xb3, 0xe8,
	0x61, 0xf6, 0x64, 0x01, 0x69, 0x5f, 0x10, 0xfd, 0x5e, 0xff, 0x31, 0x3d, 0x21, 0x5f, 0xa0, 0xb7,
	0xac, 0x23, 0x92, 0x51, 0xc8, 0xd3, 0xf0, 0xfa, 0x99, 0xbe, 0xab, 0x71, 0xe3, 0x3c, 0x87, 0x7e,
	0xdb, 0x14, 0xf2, 0x4e, 0xc3, 0x17, 0xbd, 0xf1, 0xbd, 0x16, 0xbc, 0x3a, 0xfe, 0x02, 0x06, 0x27,
	0x0d, 0x32, 0x3f, 0xbb, 0xae, 0xd4, 0xcb, 0x06, 0x69, 0xaf, 0x5e, 0xf1, 0xb7, 0xe7, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x98, 0x4c, 0x34, 0x14, 0xeb, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerAPIServiceClient is the client API for CustomerAPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerAPIServiceClient interface {
	Create(ctx context.Context, in *NewCustomerRequest, opts ...grpc.CallOption) (*Error, error)
	LoadByID(ctx context.Context, in *LoadByIDRequest, opts ...grpc.CallOption) (*LoadCustomerResponse, error)
	LoadByEmail(ctx context.Context, in *LoadByEmailRequest, opts ...grpc.CallOption) (*LoadCustomerResponse, error)
}

type customerAPIServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomerAPIServiceClient(cc *grpc.ClientConn) CustomerAPIServiceClient {
	return &customerAPIServiceClient{cc}
}

func (c *customerAPIServiceClient) Create(ctx context.Context, in *NewCustomerRequest, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/pb.CustomerAPIService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerAPIServiceClient) LoadByID(ctx context.Context, in *LoadByIDRequest, opts ...grpc.CallOption) (*LoadCustomerResponse, error) {
	out := new(LoadCustomerResponse)
	err := c.cc.Invoke(ctx, "/pb.CustomerAPIService/LoadByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerAPIServiceClient) LoadByEmail(ctx context.Context, in *LoadByEmailRequest, opts ...grpc.CallOption) (*LoadCustomerResponse, error) {
	out := new(LoadCustomerResponse)
	err := c.cc.Invoke(ctx, "/pb.CustomerAPIService/LoadByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerAPIServiceServer is the server API for CustomerAPIService service.
type CustomerAPIServiceServer interface {
	Create(context.Context, *NewCustomerRequest) (*Error, error)
	LoadByID(context.Context, *LoadByIDRequest) (*LoadCustomerResponse, error)
	LoadByEmail(context.Context, *LoadByEmailRequest) (*LoadCustomerResponse, error)
}

func RegisterCustomerAPIServiceServer(s *grpc.Server, srv CustomerAPIServiceServer) {
	s.RegisterService(&_CustomerAPIService_serviceDesc, srv)
}

func _CustomerAPIService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAPIServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CustomerAPIService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAPIServiceServer).Create(ctx, req.(*NewCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerAPIService_LoadByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAPIServiceServer).LoadByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CustomerAPIService/LoadByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAPIServiceServer).LoadByID(ctx, req.(*LoadByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerAPIService_LoadByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerAPIServiceServer).LoadByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CustomerAPIService/LoadByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerAPIServiceServer).LoadByEmail(ctx, req.(*LoadByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomerAPIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CustomerAPIService",
	HandlerType: (*CustomerAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CustomerAPIService_Create_Handler,
		},
		{
			MethodName: "LoadByID",
			Handler:    _CustomerAPIService_LoadByID_Handler,
		},
		{
			MethodName: "LoadByEmail",
			Handler:    _CustomerAPIService_LoadByEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer-service.proto",
}
